"""Add AIOPS CLI credentials to User model

Revision ID: 2023de339b1a
Revises: 538618d02253
Create Date: 2025-11-16 17:48:02.913480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2023de339b1a'
down_revision = '538618d02253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aiops_cli_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('aiops_cli_api_key', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('aiops_cli_api_key')
        batch_op.drop_column('aiops_cli_url')

    # ### end Alembic commands ###
