"""Add user-specific integration credentials

Revision ID: 296a76ac0ac1
Revises: c11f01b955f5
Create Date: 2025-11-18 09:47:29.301630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296a76ac0ac1'
down_revision = 'c11f01b955f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_integration_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('api_token', sa.Text(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['tenant_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'integration_id', name='uq_user_integration_cred')
    )
    with op.batch_alter_table('user_integration_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_integration_credentials_integration_id'), ['integration_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_integration_credentials_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_integration_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_integration_credentials_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_integration_credentials_integration_id'))

    op.drop_table('user_integration_credentials')
    # ### end Alembic commands ###
