"""Add auto_sync_enabled and sync_history table

Revision ID: 34014cadbef3
Revises: 61edecd936aa
Create Date: 2025-12-09 18:08:29.385149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34014cadbef3'
down_revision = '61edecd936aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('issues_updated', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_integration_id'], ['project_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_history_project_integration_id'), ['project_integration_id'], unique=False)

    with op.batch_alter_table('issue_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_plans_issue_id'))
        batch_op.create_index(batch_op.f('ix_issue_plans_issue_id'), ['issue_id'], unique=True)

    with op.batch_alter_table('project_integrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_sync_enabled', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_integrations', schema=None) as batch_op:
        batch_op.drop_column('auto_sync_enabled')

    with op.batch_alter_table('issue_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_plans_issue_id'))
        batch_op.create_index(batch_op.f('ix_issue_plans_issue_id'), ['issue_id'], unique=False)

    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_history_project_integration_id'))
        batch_op.drop_index(batch_op.f('ix_sync_history_created_at'))

    op.drop_table('sync_history')
    # ### end Alembic commands ###
