"""Add Claude token usage tracking to users

Revision ID: 443f6eca1717
Revises: f8b90c710eb1
Create Date: 2025-11-11 14:45:50.234602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443f6eca1717'
down_revision = 'f8b90c710eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claude_input_tokens_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_input_tokens_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_output_tokens_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_output_tokens_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_requests_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_requests_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claude_usage_last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('claude_usage_last_updated')
        batch_op.drop_column('claude_requests_remaining')
        batch_op.drop_column('claude_requests_limit')
        batch_op.drop_column('claude_output_tokens_remaining')
        batch_op.drop_column('claude_output_tokens_limit')
        batch_op.drop_column('claude_input_tokens_remaining')
        batch_op.drop_column('claude_input_tokens_limit')

    # ### end Alembic commands ###
