"""Add Slack integration models

Revision ID: 5570ca529689
Revises: 98c6d48f47df
Create Date: 2025-12-12 13:38:09.882533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5570ca529689'
down_revision = '98c6d48f47df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_user_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=32), nullable=False),
    sa.Column('slack_display_name', sa.String(length=255), nullable=True),
    sa.Column('slack_email', sa.String(length=255), nullable=True),
    sa.Column('aiops_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aiops_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slack_user_id', name='uq_tenant_slack_user')
    )
    with op.batch_alter_table('slack_user_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_user_mappings_aiops_user_id'), ['aiops_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_user_mappings_slack_user_id'), ['slack_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slack_user_mappings_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('external_issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_channel_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('slack_message_ts', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('slack_requester_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_issues', schema=None) as batch_op:
        batch_op.drop_column('slack_requester_id')
        batch_op.drop_column('slack_message_ts')
        batch_op.drop_column('slack_channel_id')

    with op.batch_alter_table('slack_user_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_user_mappings_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_slack_user_mappings_slack_user_id'))
        batch_op.drop_index(batch_op.f('ix_slack_user_mappings_aiops_user_id'))

    op.drop_table('slack_user_mappings')
    # ### end Alembic commands ###
