"""Add linux_username field to User model

Revision ID: 6236554b2a52
Revises: f32678d2f576
Create Date: 2025-11-12 11:40:06.181110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6236554b2a52'
down_revision = 'f32678d2f576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linux_username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linux_username')

    # ### end Alembic commands ###
