"""Add slack_pending_issues table

Revision ID: 697ef65dfbb7
Revises: dfc49fcad67f
Create Date: 2025-12-13 13:23:49.979818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697ef65dfbb7'
down_revision = 'dfc49fcad67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_pending_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('preview_message_ts', sa.String(length=64), nullable=False),
    sa.Column('original_message_ts', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_integration_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('created_by_slack_id', sa.String(length=64), nullable=False),
    sa.Column('requester_name', sa.String(length=256), nullable=True),
    sa.Column('requester_email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['tenant_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_integration_id'], ['project_integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slack_pending_issues', schema=None) as batch_op:
        batch_op.create_index('ix_pending_integration_expires', ['integration_id', 'expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_pending_issues', schema=None) as batch_op:
        batch_op.drop_index('ix_pending_integration_expires')

    op.drop_table('slack_pending_issues')
    # ### end Alembic commands ###
