"""Add user_identity_map table

Revision ID: 784e1b2c3a7c
Revises: 52e30c2b975b
Create Date: 2025-11-15 13:19:12.314498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784e1b2c3a7c'
down_revision = '52e30c2b975b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_identity_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('gitlab_username', sa.String(length=255), nullable=True),
    sa.Column('jira_account_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identity_map_user_id'), 'user_identity_map', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identity_map_user_id'), table_name='user_identity_map')
    op.drop_table('user_identity_map')
    # ### end Alembic commands ###
