"""Add semaphore_project_id to projects

Revision ID: 98c6d48f47df
Revises: 34014cadbef3
Create Date: 2025-12-10 14:09:43.377883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c6d48f47df'
down_revision = '34014cadbef3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semaphore_project_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('semaphore_project_id')

    # ### end Alembic commands ###
