"""Add issue_id to ai_sessions table

Revision ID: ad3a6520c17e
Revises: 296a76ac0ac1
Create Date: 2025-11-18 14:33:32.513487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3a6520c17e'
down_revision = '296a76ac0ac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ai_sessions_issue_id'), ['issue_id'], unique=False)
        batch_op.create_foreign_key('fk_ai_sessions_issue_id', 'external_issues', ['issue_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ai_sessions_issue_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_ai_sessions_issue_id'))
        batch_op.drop_column('issue_id')

    # ### end Alembic commands ###
