"""Add Activity model for tracking all aiops operations

Revision ID: b28af6ab4c87
Revises: 277aa2f31ad6
Create Date: 2025-11-19 23:52:42.519657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b28af6ab4c87'
down_revision = '277aa2f31ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('resource_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_status'))
        batch_op.drop_index(batch_op.f('ix_activities_source'))
        batch_op.drop_index(batch_op.f('ix_activities_resource_type'))
        batch_op.drop_index(batch_op.f('ix_activities_resource_id'))
        batch_op.drop_index(batch_op.f('ix_activities_action_type'))

    op.drop_table('activities')
    # ### end Alembic commands ###
