"""Add pinned_comments table

Revision ID: c2e2fc221f62
Revises: 00c220ad7017
Create Date: 2025-11-30 14:57:24.947013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e2fc221f62'
down_revision = '00c220ad7017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_issue_previews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preview_token', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('integration_id', sa.Integer(), nullable=False),
    sa.Column('issue_data', sa.JSON(), nullable=False),
    sa.Column('ai_tool', sa.String(length=50), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['project_integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_issue_previews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_issue_previews_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_issue_previews_preview_token'), ['preview_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_ai_issue_previews_user_id'), ['user_id'], unique=False)

    op.create_table('pinned_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=64), nullable=False),
    sa.Column('pinned_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['external_issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'issue_id', 'comment_id', name='uq_user_issue_comment')
    )
    with op.batch_alter_table('pinned_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pinned_comments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pinned_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pinned_comments_user_id'))

    op.drop_table('pinned_comments')
    with op.batch_alter_table('ai_issue_previews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_issue_previews_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_issue_previews_preview_token'))
        batch_op.drop_index(batch_op.f('ix_ai_issue_previews_expires_at'))

    op.drop_table('ai_issue_previews')
    # ### end Alembic commands ###
