"""Add SlackProcessedMessage for command tracking

Revision ID: dfc49fcad67f
Revises: 5570ca529689
Create Date: 2025-12-12 14:52:04.744572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc49fcad67f'
down_revision = '5570ca529689'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_processed_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('message_ts', sa.String(length=32), nullable=False),
    sa.Column('command_type', sa.String(length=32), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_ts', name='uq_slack_channel_message')
    )
    with op.batch_alter_table('slack_processed_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slack_processed_messages_channel_id'), ['channel_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slack_processed_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slack_processed_messages_channel_id'))

    op.drop_table('slack_processed_messages')
    # ### end Alembic commands ###
