"""Add SystemConfig model for Linux user mapping configuration

Revision ID: f32678d2f576
Revises: 443f6eca1717
Create Date: 2025-11-12 11:26:55.798456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f32678d2f576'
down_revision = '443f6eca1717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_config_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_config_key'))

    op.drop_table('system_config')
    # ### end Alembic commands ###
